@extends('admin.layouts.app')

@section('css')
  <link rel="stylesheet" href="{{ asset('assets/css/admin/admin_role.css') }}">
@endsection

@section('content')

<!-- ===== WRAPPER ===== -->
<div class="ar-wrapper">

    <!-- ===== MAIN ===== -->
    <div class="ar-main">

        <!-- Tabs -->
        <div class="ar-tabs">
            <button class="ar-tab active" onclick="switchTab('admin', this)">Admin</button>
            <button class="ar-tab" onclick="switchTab('role', this)">Role</button>
        </div>

        <!-- Stat Cards -->
        <div class="ar-stats">
            <div class="ar-stat-card">
                <div class="ar-stat-icon blue">👥</div>
                <div class="ar-stat-body">
                    <div class="ar-stat-label">Total Admin</div>
                    <div class="ar-stat-value">28</div>
                    <div class="ar-stat-sub">Semua admin terdaftar</div>
                </div>
            </div>
            <div class="ar-stat-card">
                <div class="ar-stat-icon green">✅</div>
                <div class="ar-stat-body">
                    <div class="ar-stat-label">Aktif</div>
                    <div class="ar-stat-value">24</div>
                    <div class="ar-stat-sub">85,7% dari total admin</div>
                </div>
            </div>
            <div class="ar-stat-card">
                <div class="ar-stat-icon orange">⏸</div>
                <div class="ar-stat-body">
                    <div class="ar-stat-label">Nonaktif</div>
                    <div class="ar-stat-value">3</div>
                    <div class="ar-stat-sub">10,7% dari total admin</div>
                </div>
            </div>
            <div class="ar-stat-card">
                <div class="ar-stat-icon red">🚫</div>
                <div class="ar-stat-body">
                    <div class="ar-stat-label">Diblokir</div>
                    <div class="ar-stat-value">1</div>
                    <div class="ar-stat-sub">3,6% dari total admin</div>
                </div>
            </div>
        </div>

        <!-- Toolbar -->
        <div class="ar-toolbar">
            <div class="ar-search-wrap">
                <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2"><circle cx="11" cy="11" r="8"/><path d="m21 21-4.3-4.3"/></svg>
                <input class="ar-input" type="text" id="ar-search" placeholder="Cari admin, email, atau no. telepon..." oninput="filterTable()">
            </div>
            <select class="ar-select" id="ar-filter-role" onchange="filterTable()">
                <option value="">Semua Role</option>
                <option value="Super Admin">Super Admin</option>
                <option value="Admin Operasional">Admin Operasional</option>
                <option value="Admin Keuangan">Admin Keuangan</option>
                <option value="Admin Customer Service">Admin Customer Service</option>
                <option value="Admin Laporan">Admin Laporan</option>
                <option value="Admin Verifikasi">Admin Verifikasi</option>
                <option value="Admin Marketing">Admin Marketing</option>
                <option value="Admin IT">Admin IT</option>
            </select>
            <select class="ar-select" id="ar-filter-status" onchange="filterTable()">
                <option value="">Status</option>
                <option value="Aktif">Aktif</option>
                <option value="Nonaktif">Nonaktif</option>
                <option value="Diblokir">Diblokir</option>
            </select>
            <button class="ar-btn ar-btn-outline" onclick="resetFilter()">
                <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2"><path d="M3 6h18M7 12h10M11 18h2"/></svg>
                Filter
            </button>
            <button class="ar-btn ar-btn-primary" onclick="openModal()">
                <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M12 5v14M5 12h14"/></svg>
                Tambah Admin
            </button>
        </div>

        <!-- Table -->
        <div class="ar-table-wrap">
            <table class="ar-table" id="ar-admin-table">
                <thead>
                    <tr>
                        <th><input type="checkbox" class="ar-checkbox" id="check-all" onchange="toggleAll(this)"></th>
                        <th>Admin</th>
                        <th>Role</th>
                        <th>Email</th>
                        <th>Status</th>
                        <th>Terakhir Aktif</th>
                        <th>Aksi</th>
                    </tr>
                </thead>
                <tbody id="ar-table-body">
                    <!-- Rows generated by JS -->
                </tbody>
            </table>
            <div class="ar-pagination">
                <span id="ar-count-info">Menampilkan 1–9 dari 28 admin</span>
                <div class="ar-page-btns">
                    <button class="ar-page-btn" disabled>&#8592;</button>
                    <button class="ar-page-btn active">1</button>
                    <button class="ar-page-btn" onclick="showToast('Halaman 2', 'info')">2</button>
                    <button class="ar-page-btn" onclick="showToast('Halaman 3', 'info')">3</button>
                    <button class="ar-page-btn" onclick="showToast('Halaman 4', 'info')">4</button>
                    <button class="ar-page-btn" onclick="showToast('Halaman selanjutnya', 'info')">&#8594;</button>
                </div>
            </div>
        </div>

    </div><!-- /ar-main -->

    <!-- ===== ACTIVITY PANEL ===== -->
    <div class="ar-activity">
        <div class="ar-activity-header">
            <span class="ar-activity-title">Aktivitas Terakhir</span>
            <a href="#" class="ar-activity-see-all">Lihat Semua</a>
        </div>

        <div class="ar-act-item">
            <div class="ar-act-icon act-add">➕</div>
            <div class="ar-act-body">
                <div class="ar-act-text"><strong>Andi Pratama</strong> ditambahkan</div>
                <div class="ar-act-meta">Oleh Super Admin • 8 Mei 2024, 09:20 WIB</div>
            </div>
        </div>
        <div class="ar-act-item">
            <div class="ar-act-icon act-edit">✏️</div>
            <div class="ar-act-body">
                <div class="ar-act-text"><strong>Role Admin Keuangan</strong> diperbarui</div>
                <div class="ar-act-meta">Oleh Budi Santoso • 7 Mei 2024, 16:30 WIB</div>
            </div>
        </div>
        <div class="ar-act-item">
            <div class="ar-act-icon act-block">🚫</div>
            <div class="ar-act-body">
                <div class="ar-act-text"><strong>Agus Setiawan</strong> diblokir</div>
                <div class="ar-act-meta">Oleh Super Admin • 6 Mei 2024, 11:15 WIB</div>
            </div>
        </div>
        <div class="ar-act-item">
            <div class="ar-act-icon act-active">✅</div>
            <div class="ar-act-body">
                <div class="ar-act-text"><strong>Siti Aisyah</strong> diaktifkan</div>
                <div class="ar-act-meta">Oleh Super Admin • 5 Mei 2024, 10:05 WIB</div>
            </div>
        </div>
        <div class="ar-act-item">
            <div class="ar-act-icon act-delete">🗑️</div>
            <div class="ar-act-body">
                <div class="ar-act-text"><strong>Rina Marlina</strong> dihapus</div>
                <div class="ar-act-meta">Oleh Super Admin • 3 Mei 2024, 08:40 WIB</div>
            </div>
        </div>
    </div>

</div><!-- /ar-wrapper -->

<!-- ===== MODAL TAMBAH ADMIN ===== -->
<div class="ar-modal-overlay" id="ar-modal">
    <div class="ar-modal">
        <div class="ar-modal-header">
            <span class="ar-modal-title">Tambah Admin Baru</span>
            <button class="ar-modal-close" onclick="closeModal()">✕</button>
        </div>
        <div class="ar-form-row">
            <div class="ar-form-group">
                <label class="ar-form-label">Nama Lengkap <span>*</span></label>
                <input class="ar-form-input" type="text" placeholder="Contoh: Budi Santoso" id="form-nama">
            </div>
            <div class="ar-form-group">
                <label class="ar-form-label">No. Telepon <span>*</span></label>
                <input class="ar-form-input" type="text" placeholder="0812-xxxx-xxxx" id="form-telp">
            </div>
        </div>
        <div class="ar-form-group">
            <label class="ar-form-label">Email <span>*</span></label>
            <input class="ar-form-input" type="email" placeholder="nama@laundryhub.com" id="form-email">
        </div>
        <div class="ar-form-row">
            <div class="ar-form-group">
                <label class="ar-form-label">Role <span>*</span></label>
                <select class="ar-form-input" id="form-role">
                    <option value="">Pilih Role</option>
                    <option>Admin Operasional</option>
                    <option>Admin Keuangan</option>
                    <option>Admin Customer Service</option>
                    <option>Admin Laporan</option>
                    <option>Admin Verifikasi</option>
                    <option>Admin Marketing</option>
                    <option>Admin IT</option>
                </select>
            </div>
            <div class="ar-form-group">
                <label class="ar-form-label">Status</label>
                <select class="ar-form-input" id="form-status">
                    <option value="Aktif">Aktif</option>
                    <option value="Nonaktif">Nonaktif</option>
                </select>
            </div>
        </div>
        <div class="ar-form-group">
            <label class="ar-form-label">Password <span>*</span></label>
            <input class="ar-form-input" type="password" placeholder="Min. 8 karakter" id="form-pass">
        </div>
        <div class="ar-modal-footer">
            <button class="ar-btn ar-btn-outline" onclick="closeModal()">Batal</button>
            <button class="ar-btn ar-btn-primary" onclick="submitForm()">Simpan Admin</button>
        </div>
    </div>
</div>

<!-- ===== TOAST CONTAINER ===== -->
<div class="ar-toast-wrap" id="ar-toast-wrap"></div>


@endsection

@push('scripts')
<script>
/* ===== DATA ===== */
const adminData = [
    { id:1, nama:'Super Admin', telp:'0812-3456-7890', role:'Super Admin', email:'admin@laundryhub.com', status:'Aktif', aktif:'8 Mei 2024, 10:15 WIB', isYou:true },
    { id:2, nama:'Andi Pratama', telp:'0812-3456-7891', role:'Admin Operasional', email:'andi.pratama@laundryhub.com', status:'Aktif', aktif:'8 Mei 2024, 09:42 WIB' },
    { id:3, nama:'Budi Santoso', telp:'0812-3456-7892', role:'Admin Keuangan', email:'budi.santoso@laundryhub.com', status:'Aktif', aktif:'7 Mei 2024, 16:30 WIB' },
    { id:4, nama:'Siti Aisyah', telp:'0812-3456-7893', role:'Admin Customer Service', email:'siti.aisyah@laundryhub.com', status:'Aktif', aktif:'8 Mei 2024, 08:55 WIB' },
    { id:5, nama:'Dewi Lestari', telp:'0812-3456-7894', role:'Admin Laporan', email:'dewi.lestari@laundryhub.com', status:'Aktif', aktif:'7 Mei 2024, 14:20 WIB' },
    { id:6, nama:'Fahmi Hidayat', telp:'0812-3456-7895', role:'Admin Verifikasi', email:'fahmi.hidayat@laundryhub.com', status:'Nonaktif', aktif:'2 Mei 2024, 11:10 WIB' },
    { id:7, nama:'Rina Marlina', telp:'0812-3456-7896', role:'Admin Marketing', email:'rina.marlina@laundryhub.com', status:'Aktif', aktif:'6 Mei 2024, 17:45 WIB' },
    { id:8, nama:'Agus Setiawan', telp:'0812-3456-7897', role:'Admin IT', email:'agus.setiawan@laundryhub.com', status:'Diblokir', aktif:null },
    { id:9, nama:'Maya Sari', telp:'0812-3456-7898', role:'Admin Operasional', email:'maya.sari@laundryhub.com', status:'Aktif', aktif:'8 Mei 2024, 07:30 WIB' },
];

const roleClass = {
    'Super Admin':'role-super',
    'Admin Operasional':'role-ops',
    'Admin Keuangan':'role-keuangan',
    'Admin Customer Service':'role-cs',
    'Admin Laporan':'role-laporan',
    'Admin Verifikasi':'role-verif',
    'Admin Marketing':'role-marketing',
    'Admin IT':'role-it',
};
const statusClass = { 'Aktif':'status-aktif','Nonaktif':'status-nonaktif','Diblokir':'status-diblokir' };

function getInitials(name) {
    return name.split(' ').slice(0,2).map(w=>w[0]).join('').toUpperCase();
}

function renderRow(d) {
    const statusCls = statusClass[d.status] || '';
    const roleCls   = roleClass[d.role] || '';
    const aktif     = d.aktif ? `<span class="ar-time">${d.aktif}</span>` : `<span class="ar-time ar-time-dash">—</span>`;
    const youBadge  = d.isYou ? `<span class="ar-you-badge">Anda</span>` : '';
    return `
    <tr data-name="${d.nama.toLowerCase()}" data-email="${d.email.toLowerCase()}" data-telp="${d.telp}" data-role="${d.role}" data-status="${d.status}">
        <td><input type="checkbox" class="ar-checkbox row-check" ${d.isYou?'disabled':''}></td>
        <td>
            <div class="ar-admin-cell">
                <div class="ar-avatar">${getInitials(d.nama)}</div>
                <div>
                    <div class="ar-admin-name">${d.nama}${youBadge}</div>
                    <div class="ar-admin-phone">${d.telp}</div>
                </div>
            </div>
        </td>
        <td><span class="ar-role-badge ${roleCls}">${d.role}</span></td>
        <td style="font-size:13px;color:#6B7280;">${d.email}</td>
        <td>
            <span class="ar-status ${statusCls}">
                <span class="ar-status-dot"></span>${d.status}
            </span>
        </td>
        <td>${aktif}</td>
        <td>
            <div class="ar-dropdown" id="dd-${d.id}">
                <button class="ar-action-btn" onclick="toggleDropdown('dd-${d.id}')">
                    <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor"><circle cx="12" cy="5" r="1.5"/><circle cx="12" cy="12" r="1.5"/><circle cx="12" cy="19" r="1.5"/></svg>
                </button>
                <div class="ar-dropdown-menu">
                    <button class="ar-dropdown-item" onclick="closeDropdowns();showToast('Edit admin: ${d.nama}','info')">✏️ Edit</button>
                    <button class="ar-dropdown-item" onclick="closeDropdowns();showToast('Detail ${d.nama} dibuka','info')">👁️ Detail</button>
                    <button class="ar-dropdown-item" onclick="closeDropdowns();showToast('Reset password ${d.nama}','warning')">🔑 Reset Password</button>
                    ${d.status==='Aktif' ? `<button class="ar-dropdown-item" onclick="closeDropdowns();showToast('${d.nama} dinonaktifkan','warning')">⏸ Nonaktifkan</button>` : ''}
                    ${d.status==='Nonaktif' ? `<button class="ar-dropdown-item" onclick="closeDropdowns();showToast('${d.nama} diaktifkan','success')">▶️ Aktifkan</button>` : ''}
                    ${d.status!=='Diblokir' ? `<button class="ar-dropdown-item" onclick="closeDropdowns();showToast('${d.nama} diblokir','error')">🚫 Blokir</button>` : `<button class="ar-dropdown-item" onclick="closeDropdowns();showToast('${d.nama} dibuka blokirnya','success')">✅ Buka Blokir</button>`}
                    <div class="ar-dropdown-divider"></div>
                    <button class="ar-dropdown-item danger" onclick="closeDropdowns();confirmDelete('${d.nama}')">🗑️ Hapus</button>
                </div>
            </div>
        </td>
    </tr>`;
}

function renderTable(data) {
    const tbody = document.getElementById('ar-table-body');
    if (data.length === 0) {
        tbody.innerHTML = `<tr><td colspan="7"><div class="ar-empty"><div class="ar-empty-icon">🔍</div><div class="ar-empty-title">Tidak ada hasil</div><div class="ar-empty-sub">Coba ubah filter atau kata kunci pencarian</div></div></td></tr>`;
    } else {
        tbody.innerHTML = data.map(renderRow).join('');
    }
    document.getElementById('ar-count-info').textContent = `Menampilkan 1–${data.length} dari 28 admin`;
}

/* ===== FILTER ===== */
function filterTable() {
    const q      = document.getElementById('ar-search').value.toLowerCase();
    const role   = document.getElementById('ar-filter-role').value;
    const status = document.getElementById('ar-filter-status').value;
    const filtered = adminData.filter(d => {
        const matchQ = !q || d.nama.toLowerCase().includes(q) || d.email.toLowerCase().includes(q) || d.telp.includes(q);
        const matchR = !role   || d.role   === role;
        const matchS = !status || d.status === status;
        return matchQ && matchR && matchS;
    });
    renderTable(filtered);
}
function resetFilter() {
    document.getElementById('ar-search').value = '';
    document.getElementById('ar-filter-role').value = '';
    document.getElementById('ar-filter-status').value = '';
    renderTable(adminData);
}

/* ===== CHECKBOX ===== */
function toggleAll(el) {
    document.querySelectorAll('.row-check:not(:disabled)').forEach(c => c.checked = el.checked);
}

/* ===== DROPDOWN ===== */
function toggleDropdown(id) {
    closeDropdowns(id);
    document.getElementById(id)?.classList.toggle('open');
}
function closeDropdowns(except) {
    document.querySelectorAll('.ar-dropdown.open').forEach(d => {
        if (d.id !== except) d.classList.remove('open');
    });
}
document.addEventListener('click', e => {
    if (!e.target.closest('.ar-dropdown')) closeDropdowns();
});

/* ===== MODAL ===== */
function openModal() { document.getElementById('ar-modal').classList.add('open'); }
function closeModal() { document.getElementById('ar-modal').classList.remove('open'); }
document.getElementById('ar-modal').addEventListener('click', function(e){
    if (e.target === this) closeModal();
});
function submitForm() {
    const nama  = document.getElementById('form-nama').value.trim();
    const email = document.getElementById('form-email').value.trim();
    const role  = document.getElementById('form-role').value;
    if (!nama || !email || !role) { showToast('Lengkapi semua field wajib', 'error'); return; }
    closeModal();
    showToast(`Admin "${nama}" berhasil ditambahkan`, 'success');
}

/* ===== TABS ===== */
function switchTab(tab, el) {
    document.querySelectorAll('.ar-tab').forEach(t => t.classList.remove('active'));
    el.classList.add('active');
    if (tab === 'role') showToast('Halaman Role (coming soon)', 'info');
}

/* ===== DELETE CONFIRM ===== */
function confirmDelete(nama) {
    if (confirm(`Hapus admin "${nama}"? Tindakan ini tidak dapat dibatalkan.`)) {
        showToast(`Admin "${nama}" berhasil dihapus`, 'success');
    }
}

/* ===== TOAST ===== */
function showToast(msg, type='info') {
    const wrap = document.getElementById('ar-toast-wrap');
    const icons = { success:'✅', error:'❌', warning:'⚠️', info:'ℹ️' };
    const t = document.createElement('div');
    t.className = `ar-toast ${type==='info'?'':type}`;
    t.innerHTML = `<span>${icons[type]||'ℹ️'}</span> ${msg}`;
    wrap.appendChild(t);
    setTimeout(() => { t.style.opacity='0'; t.style.transform='translateY(8px)'; t.style.transition='all 0.3s'; setTimeout(()=>t.remove(), 300); }, 2800);
}

/* ===== INIT ===== */
renderTable(adminData);
</script>
@endpush
